### ISSUE TITLE
Can you release an arm64 version?

### ISSUE THREAD

**Issue by vft9nesd** [ColetteContreras/v2ray-ssrpanel-plugin#10]
Can you release an arm64 version?I have an arm device，thank you~~

**Comment by vft9nesd** [comment]
https://github.com/v2ray/v2ray-core/releases/tag/v4.10.0

**Comment by ColetteContreras** [comment]
I've just added it to the last release. You are able to try it, let me know if it doesn't work for you.

**Comment by vft9nesd** [comment]
thanks very much

**Comment by vft9nesd** [comment]
It can run, but I have a question, why can it only use three cores, you know, the performance of arm cpu is weak, multi-core utilization is very important~
It is not a problem that must be solved. The v2ray you released is good enough. Because the python version of the shadowsocksr server can't be multi-core, I want to try v2ray. If this problem can be solved, the performance will improve a lot.
thank you again！
![image](https://user-images.githubusercontent.com/24932999/50719778-3c2de100-10dc-11e9-9a8f-45624eaedbf2.png)

**Comment by vft9nesd** [comment]
Or do you have a way to solve the problem of multi-core utilization of the python version of shadowsocksr server?
I look at the four beautiful cores, only one core utilization is up to 100%
![image](https://user-images.githubusercontent.com/24932999/50719854-954a4480-10dd-11e9-9f1b-418a54aca908.png)

**Comment by vft9nesd** [comment]
![image](https://user-images.githubusercontent.com/24932999/50722842-37832000-1110-11e9-9b2d-c79b2f5233a3.png)
大佬牛逼~更换了armbian，速度上升了一个层次，设备的潜能还有待开发

**Comment by ColetteContreras** [comment]
It seems that if you would like to use multi-core, you should set a port range, and proper concurrency. I'm not sure about that i understood it well, here is the original post, https://github.com/v2ray/v2ray-core/issues/694.

**Comment by vft9nesd** [comment]
I hope that shadowsocksr can take advantage of multiple cpu cores.Now your v2ray has done this successfully. I hope that at this point shadowsocksr is like v2ray.
The python version of shadowsocksr can't use multiple cores. Is there any good way for you?
It can only use one core, but I think it is more classic and easy to use now than v2ray.

**Comment by vft9nesd** [comment]
The design of the python version of shadowsocksr failed to consider multi-core issues.

**Comment by ColetteContreras** [comment]
[Next-generation Shadowsocks in Go](https://github.com/shadowsocks/go-shadowsocks2) is a powerful shadowsocks implementation, you could have a look at it.
