### ISSUE TITLE
Calculate Ratio Failure 0.2.2

### ISSUE THREAD

**Issue by samac08** [ColetteContreras/v2ray-ssrpanel-plugin#11]
new 0.2.2 Still the same problem, not calculate the ratio
<a href="https://imgchr.com/i/FHn3lR"><img src="https://s2.ax1x.com/2019/01/06/FHn3lR.md.png" alt="FHn3lR.png" border="0" /></a>

**Comment by ssrpanel** [comment]
i have same question 
https://github.com/ssrpanel/SSRPanel/issues/1222

**Comment by ColetteContreras** [comment]
I released a new version which will probably solve this issue.
https://github.com/ColetteContreras/v2ray-ssrpanel-plugin/releases/tag/v0.2.3

**Comment by ssrpanel** [comment]
@ColetteContreras thank your very much ! let me try it one more time

**Comment by ssrpanel** [comment]
@ColetteContreras It works perfectly!!!

**Comment by samac08** [comment]
> I released a new version which will probably solve this issue.
> https://github.com/ColetteContreras/v2ray-ssrpanel-plugin/releases/tag/v0.2.3

@ColetteContreras 
Thanks for fixing this issue
I have tested the latest version 0.2.3,
Now the flow value should be calculated correctly.
However, I think the current calculations are very unintuitive
Should use the same calculation method of SSR
Ssr calculated value looks very intuitive

demo image
<img src="https://s2.ax1x.com/2019/01/07/FqVJiQ.png" alt="FqVJiQ.png" border="0">
<img src="https://s2.ax1x.com/2019/01/07/FqV8Ig.png" alt="FqV8Ig.png" border="0">

**Comment by ColetteContreras** [comment]
The latest version fix this bug. Thanks for your attention and your patience! Open a new issue if you have any questions.
