### ISSUE TITLE
It is recommended to integrate some examples in config.json after installing v2ray-ssrpanel-plugin

### ISSUE THREAD

**Issue by ntgeralt** [ColetteContreras/v2ray-ssrpanel-plugin#12]
If copy and paste your tls+ws example directly seems to be risky.(Json syntax problem)

**Comment by ColetteContreras** [comment]
https://www.v2ray.com/en/configuration/index.html
> V2Ray supports comments in JSON，annotated by "//" or "/* */". In an editor that doesn't support comments, they may get displayed as errors, but comments actually work fine in V2Ray.
