### ISSUE TITLE
If there is any user which vmess_id is not set, the following users will not be loaded

### ISSUE THREAD

**Issue by chocopepper** [ColetteContreras/v2ray-ssrpanel-plugin#16]
For example, if there are 4 users in user table
User1 with vmess_id "aaa-aa-aa-aa-aaa"
User2 with vmess_id "bbb-bb-bb-bb-bbb"
User3 with vmess_id *empty*
User4 with vmess_id "ddd-dd-dd-dd-ddd"
Then only User1 and User2 will be loaded and User4 will be ignored
It would be better to add one condition to db.go to avoid such issue
<pre>
func (db *DB) GetAllUsers() ([]UserModel, error) {
	users := make([]UserModel, 0)
	db.DB.Select("id, vmess_id, username").Where("enable = 1 AND u + d < transfer_enable AND vmess_id !=''").Find(&users)
	return users, nil
}
</pre>

**Comment by ColetteContreras** [comment]
I think that that v2ray should halt is better than ignore it if `vmess_id` is empty, ignore it will cause a lot of trouble, so it will halt by default. but don't worry I will add an optional config to ignore it so that you are able to control it by yourself.

**Comment by ColetteContreras** [comment]
https://github.com/ColetteContreras/v2ray-ssrpanel-plugin/releases/tag/v0.2.5
