### ISSUE TITLE
建议支持ssrpanel的“标签”功能

### ISSUE THREAD

**Issue by yulewang** [ColetteContreras/v2ray-ssrpanel-plugin#18]
现在节点上用户的增减不受ssrpanel中的标签控制，希望能实现一个filter，根据节点的标签来过滤符合标签的用户。

**Comment by dcb9** [comment]
Sounds great to me

**Comment by ssrpanel** [comment]
> 现在节点上用户的增减不受ssrpanel中的标签控制，希望能实现一个filter，根据节点的标签来过滤符合标签的用户。

not recommend.... it just need a config : level

**Comment by yulewang** [comment]
> > 现在节点上用户的增减不受ssrpanel中的标签控制，希望能实现一个filter，根据节点的标签来过滤符合标签的用户。
> 
> not recommend.... it just need a config : level

将来准备用level来控制了吗？

**Comment by ssrpanel** [comment]
标签功能是个大坑，被废弃了
