### ISSUE TITLE
使用nginx+ws+tls会出现invalid user

### ISSUE THREAD

**Issue by thank243** [ColetteContreras/v2ray-ssrpanel-plugin#2]
2018/12/21 11:44:17 [Info] [18546706] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:45548 > v2ray.com/core/proxy/vmess/encoding: invalid user
2018/12/21 11:44:19 [Info] [664806337] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:45550 > v2ray.com/core/proxy/vmess/encoding: invalid user
2018/12/21 11:44:46 [Info] [1348997546] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:45556 > v2ray.com/core/proxy/vmess/encoding: invalid user
2018/12/21 11:44:46 [Info] [3923145217] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:45558 > v2ray.com/core/proxy/vmess/encoding: invalid user
2018/12/21 11:44:47 [Info] [3535677372] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:45560 > v2ray.com/core/proxy/vmess/encoding: invalid user
2018/12/21 11:44:48 [Info] [3485961938] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:45562 > v2ray.com/core/proxy/vmess/encoding: invalid user

**Comment by thank243** [comment]
我并没有看到这些信息，是不是需要安装什么数据库驱动？

**Comment by thank243** [comment]
root@bwh:~# cat /etc/v2ray/config.json         {
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {},
  "inbounds": [{
    "port": 10000,
"listen":"127.0.0.1",
    "protocol": "vmess",
    "tag": "proxy"
  },{
    "listen": "127.0.0.1",
    "port": 10085,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
  }],
  "outbounds": [{
    "protocol": "freedom"
  }],
  "routing": {
    "rules": [{
      "type": "field",
      "inboundTag": [ "api" ],
      "outboundTag": "api"
    }],
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },

  "ssrpanel": {
    // Node id on your SSR Panel
    "nodeId": 3,
    // every N seconds
    "checkRate": 60,
    // user config
    "user": {
      // inbound tag, which inbound you would like add user to
      "inboundTag": "proxy",
      "level": 0,
      "alterId": 64,
      "security": "none"
    },
    // db connection
    "mysql": {
      "host": "127.0.0.1",
      "port": 3306,
      "user": "ssrpanel",
      "password": "xxxxxxx",
      "dbname": "ssrpanel"
    }
  }
}

**Comment by thank243** [comment]
奇了怪了，今天重新复制了遍example配置到json里面，居然运行起来了。

**Comment by ColetteContreras** [comment]
logs will be written to error log, `/var/log/v2ray/error.log`.

**Comment by thank243** [comment]
It seem that method TCP is working perfect, but the ws+tls+nginx is still display invalid user

**Comment by ColetteContreras** [comment]
Would you mind to try it with Caddy? I'm using Caddy, that's works for me properly!

Here are my configs

```
# my v2ray server config
$ cat /etc/v2ray/config.json
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {},
  "inbounds": [{
    "port": 20000,
    "protocol": "vmess",
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/d52851be-025a-4b70-929b-933cf404011f"
      }
    },
    "tag": "proxy"
  },{
    "listen": "127.0.0.1",
    "port": 10085,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
  }],
  "outbounds": [{
    "protocol": "freedom"
  }],
  "routing": {
    "rules": [{
      "type": "field",
      "inboundTag": [ "api" ],
      "outboundTag": "api"
    }],
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },

  "ssrpanel": {
    // Node id on your SSR Panel
    "nodeId": 3,
    // every N seconds
    "checkRate": 60,
    // user config
    "user": {
      // inbound tag, which inbound you would like add user to
      "inboundTag": "proxy",
      "level": 0,
      "alterId": 16,
      "security": "none"
    },
    // db connection
    "mysql": {
      "host": "127.0.0.1",
      "port": 3306,
      "user": "root",
      "password": "ssrpanel",
      "dbname": "ssrpanel"
    }
  }



}
```

```
# Caddyfile
$ cat Caddyfile
my-test-server.com
{
  proxy /d52851be-025a-4b70-929b-933cf404011f localhost:20000 {
    websocket
    header_upstream -Origin
  }
}
```

```
#local config
$ cat config.json
{
  "log" : {
    "loglevel" : "debug"
  },
  "inbound" : {
    "listen" : "127.0.0.1",
    "port" : 2080,
    "protocol" : "socks",
    "settings" : {
      "auth" : "noauth",
      "udp" : false,
      "ip" : "127.0.0.1"
    }
  },
  "outbound" : {
    "protocol" : "vmess",
    "settings" : {
      "vnext" : [
        {
          "address" : "my-test-server.com",
          "port" : 443,
          "users" : [
            {
              "id" : "c6effafd-6046-7a85-376e-b0429751c316",
              "alterId" : 16,
              "security" : "auto",
              "level" : 0
            }
          ],
          "remark" : "my-test-server"
        }
      ]
    },
    "streamSettings" : {
      "network" : "ws",
      "security" : "tls",
      "wsSettings": {
        "path": "/d52851be-025a-4b70-929b-933cf404011f"
      }
    }
  }
}
```

```
# send a test request
$ curl -i -x socks5://localhost:2080 https://ifconfig.co/json
```

thanks for your reply

btw you could use the install script to install v2ray which is supported ssrpanel
```
$ curl -L -s https://raw.githubusercontent.com/ColetteContreras/v2ray-ssrpanel-plugin/master/install-release.sh | sudo bash
```

**Comment by thank243** [comment]
Thank you for your config. It's works!!!

I forgot to add the streamSettings to the config.json.

**Comment by ColetteContreras** [comment]
lol... Perfect! :)

**Comment by ntgeralt** [comment]
I am stuck in caddy here. LOL
