### ISSUE TITLE
error....

### ISSUE THREAD

**Issue by datougansini** [ColetteContreras/v2ray-ssrpanel-plugin#21]
v2ray.com/core/common/task.Run(0xd06360, 0xc000134cc0, 0xc000095e78, 0x2, 0x2, 0x200000000, 0xc00000aba0)
	v2ray.com/core/common/task/task.go:42 +0x1ea
v2ray.com/core/proxy/dokodemo.(*DokodemoDoor).Process(0xc0001abd40, 0xd06360, 0xc000134cc0, 0x2, 0xd09220, 0xc000134ae0, 0xd06960, 0xc0001b3500, 0x4296c2, 0x8)
	v2ray.com/core/proxy/dokodemo/dokodemo.go:150 +0x7cb
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).callback(0xc000226120, 0xd09220, 0xc000134ae0)
	v2ray.com/core/app/proxyman/inbound/worker.go:94 +0x386
created by v2ray.com/core/app/proxyman/inbound.(*tcpWorker).Start.func1
	v2ray.com/core/app/proxyman/inbound/worker.go:110 +0x52

goroutine 27 [IO wait]:
internal/poll.runtime_pollWait(0x7f96861d3e30, 0x72, 0xc000094ba8)
	/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0001b4718, 0x72, 0xffffffffffffff00, 0xcfe260, 0x11fa448)
	/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0001b4718, 0xc000214000, 0x8000, 0x8000)
	/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0001b4700, 0xc000214000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc0001b4700, 0xc000214000, 0x8000, 0x8000, 0x203001, 0x41f248, 0xc007805960)
	/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000c108, 0xc000214000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/go/src/net/net.go:177 +0x68
bufio.(*Reader).Read(0xc00006baa0, 0xc00025c1f8, 0x9, 0x9, 0x20, 0xc007805940, 0x0)
	/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0xcfbb40, 0xc00006baa0, 0xc00025c1f8, 0x9, 0x9, 0x9, 0x0, 0xc000065e10, 0xc00789d1f8)
	/go/src/io/io.go:310 +0x88
io.ReadFull(0xcfbb40, 0xc00006baa0, 0xc00025c1f8, 0x9, 0x9, 0x56, 0xc000094e50, 0x429f51)
	/go/src/io/io.go:329 +0x58
golang.org/x/net/http2.readFrameHeader(0xc00025c1f8, 0x9, 0x9, 0xcfbb40, 0xc00006baa0, 0x0, 0xc000000000, 0xc0078cc210, 0xc007868300)
	golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00025c1c0, 0xc0078cc210, 0xc0078cc210, 0x0, 0x0)
	golang.org/x/net/http2/frame.go:492 +0xa3
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc00019c000)
	google.golang.org/grpc/internal/transport/http2_client.go:1218 +0x176
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	google.golang.org/grpc/internal/transport/http2_client.go:286 +0xc53

goroutine 28 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc000066740, 0x1, 0x0, 0x0, 0x0, 0x0)
	google.golang.org/grpc/internal/transport/controlbuf.go:317 +0x103
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc00006bb00, 0x0, 0x0)
	google.golang.org/grpc/internal/transport/controlbuf.go:435 +0x1ac
google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc00019c000)
	google.golang.org/grpc/internal/transport/http2_client.go:328 +0x7b
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	google.golang.org/grpc/internal/transport/http2_client.go:326 +0xdae

goroutine 31 [chan receive]:
v2ray.com/core/app/commander.(*Outbound).Dispatch(0xc0001bd700, 0xd06360, 0xc000134d50, 0xc00000abc0)
	v2ray.com/core/app/commander/outbound.go:86 +0x207
v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0001bcf40, 0xd06360, 0xc000134d50, 0xc00000abc0, 0xd06d60, 0xc000185ee8, 0x200000000)
	v2ray.com/core/app/dispatcher/default.go:266 +0x9b
created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
	v2ray.com/core/app/dispatcher/default.go:199 +0x215

goroutine 32 [IO wait]:
internal/poll.runtime_pollWait(0x7f96861d3c90, 0x72, 0xc00027bb70)
	/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0001b4818, 0x72, 0xffffffffffffff00, 0xcfe260, 0x11fa448)
	/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0001b4818, 0xc0078fc300, 0x1, 0x1)
	/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0001b4800, 0xc0078fc368, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc0001b4800, 0xc0078fc368, 0x1, 0x1, 0x452bb0, 0x1, 0xc00027bc98)
	/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000c110, 0xc0078fc368, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/src/net/net.go:177 +0x68
v2ray.com/core/transport/internet.(*StatCouterConnection).Read(0xc000134ae0, 0xc0078fc368, 0x1, 0x1, 0xc0001d1980, 0x0, 0x0)
	v2ray.com/core/transport/internet/connection.go:20 +0x55
v2ray.com/core/common/buf.ReadBuffer(0x7f96861dbdb8, 0xc000134ae0, 0x1, 0x1, 0x0)
	v2ray.com/core/common/buf/reader.go:31 +0x6a
v2ray.com/core/common/buf.(*SingleReader).ReadMultiBuffer(0xc000065fb0, 0xc005ad1f50, 0x1, 0x1, 0x0, 0x0)
	v2ray.com/core/common/buf/reader.go:167 +0x3b
v2ray.com/core/common/buf.copyInternal(0xcfcf80, 0xc000065fb0, 0xcfd5e0, 0xc00000c138, 0xc00000ae20, 0xc00004de01, 0xc00000ae00)
	v2ray.com/core/common/buf/copy.go:79 +0x49
v2ray.com/core/common/buf.Copy(0xcfcf80, 0xc000065fb0, 0xcfd5e0, 0xc00000c138, 0xc00004df50, 0x1, 0x1, 0x0, 0x0)
	v2ray.com/core/common/buf/copy.go:102 +0xa8
v2ray.com/core/proxy/dokodemo.(*DokodemoDoor).Process.func1(0x0, 0x0)
	v2ray.com/core/proxy/dokodemo/dokodemo.go:110 +0x163
v2ray.com/core/common/task.OnSuccess.func1(0x0, 0x0)
	v2ray.com/core/common/task/task.go:12 +0x2f
v2ray.com/core/common/task.Run.func1(0xc00000c160, 0xc00006bc80, 0xc00000ac00)
	v2ray.com/core/common/task/task.go:28 +0x2b
created by v2ray.com/core/common/task.Run
	v2ray.com/core/common/task/task.go:27 +0xd7

goroutine 33 [select]:
v2ray.com/core/transport/pipe.(*pipe).ReadMultiBuffer(0xc000080be0, 0x0, 0x1, 0x0, 0x5aba3f, 0x0)
	v2ray.com/core/transport/pipe/impl.go:89 +0x102
v2ray.com/core/transport/pipe.(*Reader).ReadMultiBuffer(0xc00000c150, 0xc005ad1f30, 0x1, 0x1, 0x0, 0x0)
	v2ray.com/core/transport/pipe/reader.go:16 +0x2e
v2ray.com/core/common/buf.copyInternal(0xcfd5c0, 0xc00000c150, 0xcfcf60, 0xc000065f00, 0xc00000ac60, 0xc000012601, 0xc00000ac20)
	v2ray.com/core/common/buf/copy.go:79 +0x49
v2ray.com/core/common/buf.Copy(0xcfd5c0, 0xc00000c150, 0xcfcf60, 0xc000065f00, 0xc000012760, 0x1, 0x1, 0x0, 0x0)
	v2ray.com/core/common/buf/copy.go:102 +0xa8
v2ray.com/core/proxy/dokodemo.(*DokodemoDoor).Process.func2(0x0, 0x0)
	v2ray.com/core/proxy/dokodemo/dokodemo.go:143 +0x2dc
v2ray.com/core/common/task.Run.func1(0xc00000c160, 0xc00006bc80, 0xc0002263f0)
	v2ray.com/core/common/task/task.go:28 +0x2b
created by v2ray.com/core/common/task.Run
	v2ray.com/core/common/task/task.go:27 +0xd7

goroutine 35 [runnable]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc000066980, 0x1, 0x0, 0x0, 0x0, 0x0)
	google.golang.org/grpc/internal/transport/controlbuf.go:317 +0x103
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc00017c0c0, 0x0, 0x0)
	google.golang.org/grpc/internal/transport/controlbuf.go:435 +0x1ac
google.golang.org/grpc/internal/transport.newHTTP2Server.func2(0xc0001d1e00)
	google.golang.org/grpc/internal/transport/http2_server.go:276 +0xcb
created by google.golang.org/grpc/internal/transport.newHTTP2Server
	google.golang.org/grpc/internal/transport/http2_server.go:273 +0xe87

goroutine 36 [select]:
google.golang.org/grpc/internal/transport.(*http2Server).keepalive(0xc0001d1e00)
	google.golang.org/grpc/internal/transport/http2_server.go:921 +0x1e4
created by google.golang.org/grpc/internal/transport.newHTTP2Server
	google.golang.org/grpc/internal/transport/http2_server.go:282 +0xeac

goroutine 37 [select]:
v2ray.com/core/transport/pipe.(*pipe).ReadMultiBuffer(0xc000080b90, 0x37, 0x8, 0xc007805c40, 0xc0078cc570, 0xc350ae)
	v2ray.com/core/transport/pipe/impl.go:89 +0x102
v2ray.com/core/transport/pipe.(*Reader).ReadMultiBuffer(0xc00000c130, 0x0, 0x0, 0xc0078cc501, 0x7f96861cc163, 0xc007805c80)
	v2ray.com/core/transport/pipe/reader.go:16 +0x2e
v2ray.com/core/common/buf.(*BufferedReader).Read(0xc000134e70, 0xc00027c000, 0x8000, 0x8000, 0xc0001b0300, 0xc007805c80, 0x0)
	v2ray.com/core/common/buf/reader.go:86 +0x86
v2ray.com/core/common/net.(*connection).Read(0xc000080cd0, 0xc00027c000, 0x8000, 0x8000, 0xc00003d290, 0xc00003c000, 0xc00027ace0)
	v2ray.com/core/common/net/connection.go:87 +0x4c
bufio.(*Reader).Read(0xc00006bf80, 0xc00025c3b8, 0x9, 0x9, 0xc0078ca548, 0xc0078cc5d0, 0xc00027ad78)
	/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0xcfbb40, 0xc00006bf80, 0xc00025c3b8, 0x9, 0x9, 0x9, 0xc00027ada0, 0x7cf2ad, 0xc0078ca540)
	/go/src/io/io.go:310 +0x88
io.ReadFull(0xcfbb40, 0xc00006bf80, 0xc00025c3b8, 0x9, 0x9, 0xc007868600, 0x0, 0x0)
	/go/src/io/io.go:329 +0x58
golang.org/x/net/http2.readFrameHeader(0xc00025c3b8, 0x9, 0x9, 0xcfbb40, 0xc00006bf80, 0x0, 0xcff00000000, 0xaa00010001, 0x1000100000cff)
	golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00025c380, 0xc000134ed0, 0xc000134ed0, 0x0, 0x0)
	golang.org/x/net/http2/frame.go:492 +0xa3
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc0001d1e00, 0xc0001350b0, 0xc605e0)
	google.golang.org/grpc/internal/transport/http2_server.go:429 +0x7c
google.golang.org/grpc.(*Server).serveStreams(0xc0001d0a80, 0xd09d60, 0xc0001d1e00)
	google.golang.org/grpc/server.go:681 +0xdd
google.golang.org/grpc.(*Server).handleRawConn.func1(0xc0001d0a80, 0xd09d60, 0xc0001d1e00)
	google.golang.org/grpc/server.go:643 +0x43
created by google.golang.org/grpc.(*Server).handleRawCon

**Comment by ColetteContreras** [comment]
Hmmm i don't know why. Have you solved the problem?
