### ISSUE TITLE
自己在config里添加trafficRate字段之后，后续修改无效

### ISSUE THREAD

**Issue by PlaneV** [ColetteContreras/v2ray-ssrpanel-plugin#23]
各位好！我在config里面手动加了trafficRate字段，为了测试调整到了10倍，现在想把这个值调小，发现无论调成什么值都一直是10倍，有什么办法吗？

**Comment by samac08** [comment]
流量比例提取的节点值的 配置无设置参数 你的问题再面板修改即可

**Comment by PlaneV** [comment]
> 流量比例提取的节点值的 配置无设置参数 你的问题再面板修改即可

it's works! thx!
