### ISSUE TITLE
请教如何把v2ray-core升级到4.18？

### ISSUE THREAD

**Issue by PlaneV** [ColetteContreras/v2ray-ssrpanel-plugin#24]
你好！我最近在测试这个插件，但是发现插件自动带来的是4.9版，路由器客户端是4.18，测试发现不能兼容，有什么办法可以升级自带的服务端版本吗？谢谢！

**Comment by ColetteContreras** [comment]
I'll try to release a version for you later. I'm not sure that whether upgrade will encounter any problems.

**Comment by PlaneV** [comment]
OK, Thanks man.
