### ISSUE TITLE
装完之后 和 ssrpanel 对接之后 数据库 做了一些访问之后 ，user的 ip 表还是空的 

### ISSUE THREAD

**Issue by Uhtred009** [ColetteContreras/v2ray-ssrpanel-plugin#25]

**Comment by Uhtred009** [comment]
装的 3.0的

**Comment by ColetteContreras** [comment]
You may forget to update `config.json`, follow the post, [How to track user ip?](https://github.com/ColetteContreras/v2ray-ssrpanel-plugin/wiki/How-to-track-user-ip%3F), and reach it.
