### ISSUE TITLE
v2ray对接ssrpanel上不了网

### ISSUE THREAD

**Issue by yanlianglai** [ColetteContreras/v2ray-ssrpanel-plugin#29]
v2ray正常运行，ssrpanel后台也检测到了v2ray，但是就是上不了网！！！！
config.json 配置文件
{
  "log": {
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {},
  "inbounds": [
    {
    "listen": "127.0.0.1",
    "port": 10087,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
    },
    {
      "tag": "proxy",
      "port": 10086,
      "protocol": "vmess",
      "settings": {
        "clients": [],
        "disableInsecureEncryption": false,
        "default": {
          "level": 0,
          "alterId": 16
        }
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/game"
        }
      }
    }
  ],
  "outbounds": [{
    "protocol": "freedom"
  }],
  "routing": {
    "rules": [{
      "type": "field",
      "inboundTag": [ "api" ],
      "outboundTag": "api"
    }],    
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },

  "ssrpanel": {
    // Node id on your SSR Panel
    "nodeId": 4,
    // every N seconds
    "checkRate": 300,
    // user config
    "user": {
      // inbound tag, which inbound you would like add user to
      "inboundTag": "proxy",
      "level": 0,
      "alterId": 16,
      "security": "none"
    },
    // db connection
    "mysql": {
      "host": "127.0.0.1",
      "port": 3306,
      "user": "ssrpanel",
      "password": "4565",
      "dbname": "ssrpanel"
    }
  }
}

我的v2ray运行状态
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; disabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-07-21 13:45:47 CST; 45min ago
 Main PID: 31239 (v2ray)
   CGroup: /system.slice/v2ray.service
           └─31239 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Jul 21 13:45:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 13:45:51 [Debug] SSRPanelPlugin: + 1 users, - 0 users, ↓ 0, ↑ 0, online 0
Jul 21 13:50:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 13:50:51 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jul 21 13:55:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 13:55:51 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jul 21 14:00:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 14:00:51 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jul 21 14:05:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 14:05:51 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jul 21 14:10:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 14:10:51 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jul 21 14:15:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 14:15:51 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jul 21 14:20:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 14:20:51 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jul 21 14:25:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 14:25:51 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jul 21 14:30:51 fine-bounty-1.localdomain v2ray[31239]: 2019/07/21 14:30:51 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0

我不知道我错了哪里，是不是我的ssrpanel里面的v2ray配置错误 ？还是别的地方？求大神指教

**Comment by ntgeralt** [comment]
10086改为10085

**Comment by yanlianglai** [comment]
已经好了 v2ray配置问题
