### ISSUE TITLE
这个是直接编译到V2内核中了 ?

### ISSUE THREAD

**Issue by samac08** [ColetteContreras/v2ray-ssrpanel-plugin#3]
4.9版本 这个是直接编译进v2内核中了吧 ? 具体用法能否示例下   测试错误如下 配置及程序都无误 提示错误如下 

ines 1-14/14 (END)...skipping...
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-12-22 19:40:18 CST; 284ms ago
 Main PID: 10236 (v2ray)
    Tasks: 7 (limit: 4915)
   CGroup: /system.slice/v2ray.service
           └─10236 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Dec 22 19:40:18 ip-172-26-43-102 systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Dec 22 19:40:18 ip-172-26-43-102 systemd[1]: Stopped V2Ray Service.
Dec 22 19:40:18 ip-172-26-43-102 systemd[1]: Started V2Ray Service.
Dec 22 19:40:18 ip-172-26-43-102 v2ray[10236]: V2Ray 4.9 (Po) Custom
Dec 22 19:40:18 ip-172-26-43-102 v2ray[10236]: A unified platform for anti-censorship.
Dec 22 19:40:18 ip-172-26-43-102 v2ray[10236]: 2018/12/22 19:40:18 [Error] SSRPanelPlugin: failed to load config:  > v2ray.com/core/main/confloader/external: config file not readable > open : no such file or directory

<a href="https://imgchr.com/i/FyZcBF"><img src="https://s1.ax1x.com/2018/12/22/FyZcBF.md.png" alt="FyZcBF.png" border="0" /></a>

**Comment by thank243** [comment]
那么明显，无法读书配置文件。确认/etc/v2ray里面有？

**Comment by samac08** [comment]
没有配置文件 .这种低级错误还是不会犯的. 配置文件没有任何问题 我Java都一直在用 ......

**Comment by samac08** [comment]
> ls -al /etc/v2ray
> 看下结果
drwxr-xr-x  2 root root 4096 Dec 22 15:54 .
drwxr-xr-x 75 root root 4096 Dec 22 15:54 ..
-rwxrwxrwx  1 root root 2020 Dec 22 16:00 config.json

**Comment by thank243** [comment]
应该还是配置文件的问题，4.9这个版本配置文件又更新了。

**Comment by samac08** [comment]
配置在原版内核及Java后端测试都是ok的  在此mod就是不行 
{
    "log": {
        "access": "./access.log",
        "error": "./error.log",
        "loglevel": "debug"
    },
    "api": {
        "services": [
            "HandlerService",
            "LoggerService",
            "StatsService"
        ],
        "tag": "api"
    },
    "stats": {},
    "inbounds": [{
            "listen": "127.0.0.1",
            "port": 10086,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "tag": "api"
        },
        {
            "tag": "proxy",
            "listen": "127.0.0.1",
            "port": 10085,
            "protocol": "vmess",
            "settings": {
                "clients": [],
                "disableInsecureEncryption": true,
                "default": {
                    "level": 0,
                    "alterId": 16
                }
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/wsx"
                }
            }
        }
    ],
    "outbounds": [{
        "protocol": "freedom",
        "settings": {}
    }],
    "routing": {
        "rules": [{
            "inboundTag": [
                "api"
            ],
            "outboundTag": "api",
            "type": "field"
        }]
    },
    "policy": {
        "levels": {
            "1": {
                "statsUserUplink": true,
                "statsUserDownlink": true
            }
        }
    },
    "ssrpanel": {
        "nodeId": 1,
        "checkRate": 60,
        "user": {
            "inboundTag": "proxy",
            "level": 0,
            "alterId": 16,
            "security": "none"
        },
        "mysql": {
            "host": "xxx",
            "port": 3306,
            "user": "xxx",
            "password": "xxx",
            "dbname": "xxx"
        }
    }
}

**Comment by ColetteContreras** [comment]
@samac08 
It is a bug which says that SSRPanel failed to load config, the latest release has fixed the bug.

you are able install latest v2ray version by a script below:

```
$ curl -L -s https://raw.githubusercontent.com/ColetteContreras/v2ray-ssrpanel-plugin/master/install-release.sh | sudo bash
```

You are more than welcome to report issues!

@thank243 thanks for your help anyway

**Comment by samac08** [comment]
> @samac08
> It is a bug which says that SSRPanel failed to load config, the latest release has fixed the bug.
> 
> you are able install latest v2ray version by a script below:
> 
> ```
> $ curl -L -s https://raw.githubusercontent.com/ColetteContreras/v2ray-ssrpanel-plugin/master/install-release.sh | sudo bash
> ```
> You are more than welcome to report issues!
> 
> @thank243 thanks for your help anyway

Thanks for fixing this error,
This version is now working .
1. But can't view database connection and access information ,at acces.log; 
2. ssrpanel not displayed online users  zero.  ( SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
)

**Comment by thank243** [comment]
plz,use journalctl -u v2ray.service to see logs, if you are not set the access.log's address.

**Comment by samac08** [comment]
Log problem restart solved. 2 .3 need Optimization.
This is a very good mod, very nice for small  ram vps. Smaller memory usage only 30m ,I have been to find an alternative of java mod.

**Comment by samac08** [comment]
> plz,use journalctl -u v2ray.service to see logs, if you are not set the access.log's path.
Log problem restart solved. 2 .3 need Optimization.

**Comment by samac08** [comment]
Now all problems are solved
The configuration must be strictly in the New 4.9 format.
No longer compatible with legacy formats
Test result .Perfect
Say goodbye to java !
