### ISSUE TITLE
How to compile my own version v2ray with different database table name and column name?

### ISSUE THREAD

**Issue by zhwalker** [ColetteContreras/v2ray-ssrpanel-plugin#4]
The table name and column name in my database is different from ssrpanel. I know I can edit db.go file but I don't know how to build my own version of v2ray.

**Comment by ColetteContreras** [comment]
First of all, you have to [install Bazel](https://docs.bazel.build/versions/master/install.html) to build v2ray from source code.

After installing Bazel, clone v2ray source code, v2ray-core and v2ray-ext.

```
go get -u v2ray.com/ext/...

cd $GOPATH/v2ray.com/
git clone https://github.com/ColetteContreras/v2ray-core.git core
cd core
git checkout -b SSRPanelPlugin-v4.9.0 --track origin/SSRPanelPlugin-v4.9.0
```

Then, build your own v2ray binary

```
bazel clean \
  && bazel build \
    --action_env=GOPATH=$GOPATH \
    --action_env=PATH=$PATH \
    //release:v2ray_darwin_amd64_package
```

Output files is located at `./bazel-bin/release/`

Enjoy your coding :)

**Comment by Iant20** [comment]
v2ray.com/ext has been deprecated, this doesn't work now, how to fix this?
