### ISSUE TITLE
大佬，安装完成后报错

### ISSUE THREAD

**Issue by victoryLV** [ColetteContreras/v2ray-ssrpanel-plugin#5]
-- Logs begin at Tue 2019-01-01 22:55:34 EST, end at Fri 2019-01-04 03:05:32 EST. --
Jan 03 20:45:33 Nathosts-20191239 systemd[1]: Started V2Ray Service.
Jan 03 20:45:33 Nathosts-20191239 systemd[1]: Starting V2Ray Service...
Jan 03 20:45:33 Nathosts-20191239 v2ray[16663]: V2Ray 4.9 (Po) Custom
Jan 03 20:45:33 Nathosts-20191239 v2ray[16663]: A unified platform for anti-censorship.
Jan 03 20:45:33 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:33 [Debug] v2ray.com/core/app/log: Logger started
Jan 03 20:45:33 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:33 [Warning] v2ray.com/core: V2Ray 4.9 started
Jan 03 20:45:34 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:34 [Info] SSRPanelPlugin: Connecting database...
Jan 03 20:45:34 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:34 [Info] SSRPanelPlugin: Connected
Jan 03 20:45:35 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:35 [Warning] SSRPanelPlugin: Connected gRPC server "127.0.0.1:13145"
Jan 03 20:45:35 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:35 [Debug] [2286056426] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:33675
Jan 03 20:45:35 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:35 [Info] [2286056426] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
Jan 03 20:45:35 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:35 [Debug] SSRPanelPlugin: node traffic rate 1.00
Jan 03 20:45:35 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:35 [Debug] SSRPanelPlugin: start jobs
Jan 03 20:45:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:45:36 [Warning] SSRPanelPlugin: + 102 users, - 0 users, ↓ 0, ↑ 0, online 0
Jan 03 20:50:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:50:36 [Debug] SSRPanelPlugin: start jobs
Jan 03 20:50:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:50:36 [Warning] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jan 03 20:55:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:55:36 [Debug] SSRPanelPlugin: start jobs
Jan 03 20:55:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 20:55:36 [Warning] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jan 03 21:00:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 21:00:36 [Debug] SSRPanelPlugin: start jobs
Jan 03 21:00:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 21:00:36 [Warning] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jan 03 21:05:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 21:05:36 [Debug] SSRPanelPlugin: start jobs
Jan 03 21:05:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 21:05:36 [Warning] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jan 03 21:10:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 21:10:36 [Debug] SSRPanelPlugin: start jobs
Jan 03 21:10:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 21:10:36 [Warning] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jan 03 21:15:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 21:15:36 [Debug] SSRPanelPlugin: start jobs
Jan 03 21:15:36 Nathosts-20191239 v2ray[16663]: 2019/01/03 21:15:36 [Warning] SSRPanelPlugin: + 0 users, - 0 users, ↓ 0, ↑ 0, online 0
Jan 03 21:19:34 Nathosts-20191239 systemd[1]: Stopping V2Ray Service...
Jan 03 21:19:34 Nathosts-20191239 v2ray[16663]: 2019/01/03 21:19:34 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp [::]:13144: use
Jan 03 21:19:34 Nathosts-20191239 systemd[1]: Stopped V2Ray Service.
Jan 04 03:05:23 Nathosts-20191239 systemd[1]: Started V2Ray Service.
Jan 04 03:05:23 Nathosts-20191239 systemd[1]: Starting V2Ray Service...
Jan 04 03:05:23 Nathosts-20191239 v2ray[18432]: V2Ray 4.9 (Po) Custom
Jan 04 03:05:23 Nathosts-20191239 v2ray[18432]: A unified platform for anti-censorship.
Jan 04 03:05:23 Nathosts-20191239 v2ray[18432]: 2019/01/04 03:05:23 [Debug] v2ray.com/core/app/log: Logger started
Jan 04 03:05:23 Nathosts-20191239 v2ray[18432]: 2019/01/04 03:05:23 [Warning] v2ray.com/core: V2Ray 4.9 started
Jan 04 03:05:24 Nathosts-20191239 v2ray[18432]: 2019/01/04 03:05:24 [Info] SSRPanelPlugin: Connecting database...
Jan 04 03:05:24 Nathosts-20191239 v2ray[18432]: 2019/01/04 03:05:24 [Info] SSRPanelPlugin: Connected
Jan 04 03:05:24 Nathosts-20191239 v2ray[18432]: 2019/01/04 03:05:24 [Warning] SSRPanelPlugin: Connected gRPC server "127.0.0.1:13145"
Jan 04 03:05:24 Nathosts-20191239 v2ray[18432]: 2019/01/04 03:05:24 [Debug] [2677682272] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:40194
Jan 04 03:05:24 Nathosts-20191239 v2ray[18432]: 2019/01/04 03:05:24 [Info] [2677682272] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]

**Comment by ColetteContreras** [comment]
It seems that your configuration is incorrect! You can paste your configs here, so that we may be able to correct it.
btw i fond that there are several people have encountered this problem, [Google: websocket: failed to serve http for WebSocket](https://www.google.com/search?q=websocket%3A%20failed%20to%20serve%20http%20for%20WebSocket%20%20), you can try it to solve the problem.

**Comment by thank243** [comment]
报错？我怎么没看到
